name: mixins_weebi
homepage: http://weebi.com
version: 0.1.6
#publish_to: none # https://onepub.dev/api/xnxpsdavuh/
description: mixins and all about mobx stores

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  collection: ^1.14.12
  mobx: ^2.2.0
  provider: ^6.0.5

  models_weebi: ^1.0.18
  services_weebi: ^1.0.8

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  #flutter_lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4