name: mixins_weebi
homepage: http://weebi.com
version: 0.0.1
publish_to: https://onepub.dev/api/xnxpsdavuh/
description: A starting point for Dart libraries or applications.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^6.0.3
  mobx: ^2.0.1
  collection: ^1.15.0
  models_weebi:
    hosted:
      url: https://onepub.dev/api/xnxpsdavuh/
      name: models_weebi
      version: ^1.0.7
  services_weebi:
    hosted:
      url: https://onepub.dev/api/xnxpsdavuh/
      name: services_weebi
      version: ^1.0.1

dev_dependencies:
  test: ^1.16.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4
flutter: null