name: mixins_weebi
description: A new Flutter package project.
homepage: 'http://weebi.com'
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0" #'>=2.18.4 <3.0.0'

dependencies:
  provider: ^6.0.3
  mobx: ^2.0.1
  models_weebi:
    hosted:
      url: https://onepub.dev/api/xnxpsdavuh/
      name: models_weebi
  services_weebi:
    hosted:
      url: https://onepub.dev/api/xnxpsdavuh/
      name: services_weebi
    #version: ^1.0.1
  


dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  #flutter_lints: ^2.0.0
  build_runner: ^2.1.11 #^1.12.2 #^1.10.2
  mobx_codegen: ^2.0.1+3
