name: mixins_weebi
homepage: http://weebi.com
version: 0.0.9
publish_to: none # https://onepub.dev/api/xnxpsdavuh/
description: mixines and all about mobx stores

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  mobx: ^2.0.1
  collection: ^1.15.0
  models_weebi:
    git:
      url: https://github.com/weebi-com/models
    #path: ../models_weebi 
    #hosted:
    #  url: https://onepub.dev/api/xnxpsdavuh/
    #  name: models_weebi
    #version: ^1.0.11
  services_weebi:
    git:
      url: https://github.com/weebi-com/services
    #path: ../services_weebi
    #hosted:
    #  url: https://onepub.dev/api/xnxpsdavuh/
    #  name: services_weebi
    #version: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4