name: mixins_weebi
homepage: http://weebi.com
version: 0.0.9
#publish_to: none # https://onepub.dev/api/xnxpsdavuh/
description: mixins and all about mobx stores

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.14.12
  mobx: ^2.0.1
  provider: ^6.0.3

  models_weebi: ^1.0.13
    #path: ../models_weebi 
  services_weebi: ^1.0.4
    #path: ../services_weebi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4